[DEVOPS-1566] - add DCT test workflow
bitwarden/self-host pull request #158
Opened 2023-09-29 21:46 UTC by Eeebru

- add DCT test workflow

2023-10-03 17:08 UTC, mimartin12 requested changes

2023-10-03 17:08 UTC, mimartin12 commented on .github/workflows/DCT-test.yml
> +          docker tag $_AZ_REGISTRY/$_PROJECT_NAME:$_IMAGE_TAG bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
```suggestion
        run: docker tag $_AZ_REGISTRY/$_PROJECT_NAME:$_IMAGE_TAG bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
```
🎨 
Single line for the `run` command, or maybe consider merging this step with the one above.

2023-10-03 17:08 UTC, mimartin12 commented on .github/workflows/DCT-test.yml
> +          docker push bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
🎨  single line for `run` command.
```suggestion
        run: docker push bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
```

2023-10-04 16:19 UTC, vgrassia reviewed
What is the purpose of this workflow?  Do we need the ability to push any image manually to Docker Hub?

2023-10-05 12:40 UTC, Eeebru commented
> What is the purpose of this workflow? Do we need the ability to push any image manually to Docker Hub?

This is only used when we create a new repository on DH to test if the signing is working.

2023-10-09 21:03 UTC, vgrassia commented
To make this more secure, can the workflow have all inputs removed and pinned for `mssqlmigratorutility` and then move this whole workflow over to the `devops` repository? I can see this being an issue if someone runs the workflow with the wrong image/tag and deploys a signed image to one of our Docker Hub repositories.

2023-10-10 14:25 UTC, Eeebru commented
> To make this more secure, can the workflow have all inputs removed and pinned for `mssqlmigratorutility` and then move this whole workflow over to the `devops` repository? I can see this being an issue if someone runs the workflow with the wrong image/tag and deploys a signed image to one of our Docker Hub repositories.

Okay, will update the workflow reference only `mssqlmigratorutility`, however, Joseph suggested the workflow to be here. We can have the conversation on our Team sync.

2023-10-12 12:57 UTC, Eeebru commented
Hello @vgrassia, at the team sync yesterday, Joseph said he would leave me to make the decision of where this test wf should be. I am of the opinion that self-host is the only place where we are pushing any images to DH, so it makes sense if we leave this workflow in this repo, instead of DevOps repo. It will also be pretty redundant, since it would only be run when we add repos to DH, leaving it in the DevOps repo means we might delete it along the line when it's not being used.

2023-10-18 14:43 UTC, vgrassia requested changes

2023-10-18 14:43 UTC, vgrassia commented on .github/workflows/DCT-test.yml
> +
```suggestion
```

2023-10-18 14:43 UTC, vgrassia commented on .github/workflows/DCT-test.yml
> +          docker tag $_AZ_REGISTRY/$_PROJECT_NAME:$_IMAGE_TAG bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
```suggestion
          docker pull $_AZ_REGISTRY/$_REPO:$_IMAGE_TAG
          docker tag $_AZ_REGISTRY/$_REPO:$_IMAGE_TAG bitwarden/$_REPO:$_IMAGE_TAG
```

2023-10-18 14:43 UTC, vgrassia commented on .github/workflows/DCT-test.yml
> +        run: docker push bitwarden/$_PROJECT_NAME:$_IMAGE_TAG
```suggestion
        run: docker push bitwarden/$_REPO:$_IMAGE_TAG
```

2023-10-18 16:45 UTC, vgrassia approved these changes

2023-10-19 13:11 UTC, michalchecinski approved these changes

2023-10-19 14:39 UTC, mimartin12 approved these changes

2023-10-19 14:40 UTC, merged