Added a warning message if running the Bitwarden Install script as root
bitwarden/self-host pull request #195
Opened 2024-01-17 09:55 UTC by keithhubner

Running the install script as root causes known issues in the product. The person running the script may not realise that a dedicated user is advised in the documentation or have missed the step to create the Bitwarden user. This will also catch users who are running an update of the product as the root user, which can also cause issues. 

It is worth noting that this may result in an increase of service desk tickets for users upgrading who have historically done so as root and are now concerned.

2024-01-17 18:50 UTC, vgrassia requested changes

2024-01-17 18:50 UTC, vgrassia commented on bitwarden.sh
> +
```suggestion
    case "$choice" in
        [Yy]|[Yy][Ee][Ss])
            echo -e "Continuing...."
            ;;
        *)
            exit 1
            ;;
    esac
fi

```
Remove extra whitespace.

2024-01-18 14:27 UTC, keithhubner reviewed
removed whitespace

2024-01-22 09:29 UTC, keithhubner reviewed
Changes made

2024-01-24 17:44 UTC, vgrassia approved these changes

2024-01-24 17:45 UTC, merged