Add compressLogs Functionality to Bitwarden Self-Hosted
bitwarden/self-host pull request #225
Opened 2024-03-06 15:17 UTC by fer

## Description

Introduces a new feature to the Bitwarden self-hosted script `bitwarden.sh` – the ability to compress and archive logs within a specified date range, or all logs if no range is provided. 

This enhancement simplifies log management, particularly for troubleshooting and audit purposes, by allowing administrators to easily package relevant log files.

## Features

- [x] Compress logs between two dates (`START_DATE` and `END_DATE`) specified in `YYYYMMDD` format.
- [x] Optionally compress all logs if no date range is provided.
- [x] Validates date format and ensures `START_DATE` is not after `END_DATE`.
- [x] Creates the compressed archive in the current directory, naming it based on the date range or as "all" for complete log compression.

## Usage examples

Compress logs from March 4th, 2024 to March 5th, 2024:
```bash
./bitwarden.sh compresslogs 20240304 20240305
```

A compressed file `bitwarden-logs-20240304-to-20240305.tar.gz` is produced.

Compress all logs:
```bash
./bitwarden.sh compresslogs
```

A compress file `bitwarden-logs-all.tar.gz` is produced

## Testing

Please review this PR for inclusion in the next release of Bitwarden self-hosted. Your feedback and suggestions are welcome!

2024-03-06 16:12 UTC, vgrassia requested changes

2024-03-06 16:12 UTC, vgrassia commented on bitwarden.sh
> +
```suggestion
function compressLogs() {
    LOG_DIR=${1#$(pwd)/}/logs
    START_DATE=$2
    END_DATE=$3
    tempfile=$(mktemp)

    function validateDateFormat() {
    if ! [[ $1 =~ ^[0-9]{8}$ ]]; then
        echo "Error: $2 date format is invalid. Please use YYYYMMDD."
        exit 1
    fi
    }

    function validateDateOrder() {
        if [[ $(date -d "$1" +%s) > $(date -d "$2" +%s) ]]; then
            echo "Error: start date ($1) must be earlier than end date ($2)."
            exit 1
        fi
    }

    # Validate start date format
    if [ -n "$START_DATE" ]; then
        validateDateFormat "$START_DATE" "start"
        if [ -z "$END_DATE" ]; then
            echo "Error: an end date is required when an start date is provided."
            exit 1
        fi
    fi
    
    # Validate end date format and order
    if [ -n "$END_DATE" ]; then
        validateDateFormat "$END_DATE" "end"
        validateDateOrder "$START_DATE" "$END_DATE"
    fi

    if [ -n "$START_DATE" ] && [ -n "$END_DATE" ]; then

        OUTPUT_FILE="bitwarden-logs-${START_DATE}-to-${END_DATE}.tar.gz"

        if [[ "$START_DATE" == "$END_DATE" ]]; then
            OUTPUT_FILE="bitwarden-logs-${START_DATE}.tar.gz"
        fi

        for d in $(seq $(date -d "$START_DATE" "+%Y%m%d") $(date -d "$END_DATE" "+%Y%m%d")); do
            # Find and list files matching the date in the filename and modification time, append to tempfile
            find $LOG_DIR \( -type f -name "*$d*.txt" -o -name "*.log" -newermt "$START_DATE" ! -newermt "$END_DATE" \) -exec bash -c 'echo "${1#./}" >> "$2"' _ {} "$tempfile" \;
        done

        echo "Compressing logs from $START_DATE to $END_DATE ..."
    else
        OUTPUT_FILE="bitwarden-logs-all.tar.gz"
        find $LOG_DIR -type f -exec bash -c 'echo "${1#./}" >> "$2"' bash {} "$tempfile" \;
        echo "Compressing all logs..."
    fi

    tar -czvf "$OUTPUT_FILE" -T "$tempfile"
    echo "Logs compressed into $(pwd $OUTPUT_FILE)/$OUTPUT_FILE"
    rm $tempfile
}

```

2024-03-08 16:41 UTC, keithhubner approved these changes
I have tested and works as expected.

2024-03-08 16:59 UTC, fer commented on bitwarden.sh
> +
@vgrassia We just merged your proposal onto our changes.

2024-03-11 13:22 UTC, merged